### PR TITLE
Added a way to try out swift on build-podcast with glot.io

### PR DESCRIPTION
**Pull request by strages**
Glot.io is an awesome way to run code snippets in the browser in a secure docker environment! :) Thought it might add value to build-podcast website!

### CODE REVIEW

**Comment by sayanee** [comment]
Wow cool! Thanks for the link ☺️

I don't think you can see an `iframe` on a `readme.md` file. Maybe you can amend it to a hyperlink instead?

**Comment by strages** [comment]
Hi sayanee, 

What do you mean? :)

_posts/2016-04-09-swift.md is converted to html for the website isn't it? I believe it supports html

**Comment by sayanee** [comment]
You are right @strages - let me merge and deploy to test!

**Comment by sayanee** [comment]
Yes it looks great: https://build-podcast.com/swift/ 😍

image

**Comment by strages** [comment]
Awesome!

**Pull request merged**
